---
title: "Functional Interpretation"
output: html_document
---

```{r warning = FALSE, message = FALSE}
#reading results from a dataset
library(dplyr)
library(rlist)
source("process_annotation_DB.R")

load("my_data_filtered_matched_1h")

head(my_data_filtered_matched)

all = my_data_filtered_matched[my_data_filtered_matched$genes %in% processed_pathways[[153]][[6]]$genes, c("type", "prof_index")]

#all = my_data_filtered_matched[,c("type", "prof_index")]
#all = all[all$prof_index != 2, ]


all_df = data.frame(unique(all), as.numeric(row.names(unique(all))))

all_df = count(all, c("type", "prof_index"))
names(all_df) = c("type", "profile", "Freq")

#all_df = all_df[all_df$Freq >25,]

all_df[all_df$type == 'A', 'type'] = 'additive'
all_df[all_df$type == 'P', 'type'] = 'synerg'
all_df[all_df$type == 'N', 'type'] = 'antag'

col = vector()
col[all_df$type == 'additive'] = 'gray50'
col[all_df$type == 'synerg'] = 'cornflowerblue'
col[all_df$type == 'antag'] = 'red'



alluvial(all_df[,c(1, 2)], freq = all_df$Freq,
         col = col,
         border = col,
         hide = all_df$Freq < 2,
         cex = 1
)



#remove constant genes
background_genes = filter(my_data_filtered_matched, 
                          my_data_filtered_matched$prof_index != 2)

processed_pathways = process_annotation_DB(background_genes, 'GO_Biological_Process_2017b.txt')


#association
#fisher_pvalues = sapply(processed_pathways, function(x) x[[9]])
chi_pvalues = sapply(processed_pathways, function(x) x[[5]])

#get additivity fraction
additivity_level = sapply(processed_pathways, function(x) x[[8]][2,1])

processed_pathway_names = sapply(processed_pathways, function(x) x[[1]])

processed_pathway_names = gsub("\\(GO:", "", processed_pathway_names, perl=TRUE)

processed_pathway_names = gsub("[0-9]", "", processed_pathway_names, perl=TRUE)

processed_pathway_names = gsub(" \\)", "", processed_pathway_names, perl=TRUE)

#c(7, 12, 13, 14, 15, 19, 15, 9, 17, 20)
#selected_pathway_idx = order(additivity_level, decreasing = #T)[111:120]

#GEO
#selected_pathway_idx = order(additivity_level, decreasing = T)[c(1, 5, 25, 26, 28, 29, 30, 32, 33, 44, 56, 57, 64, 65, 73, 77, 79, 86,
#                                              100, 102, 112, 113)]

ind = order(chi_pvalues)[19]
shift = sort(processed_pathways[[ind]][[8]][2,] - processed_pathways[[ind]][[8]][1,]) 

profiles = background_genes$type
names(profiles) = background_genes$prof_index
cols = as.vector(profiles[names(shift)])
cols[cols == 'A'] = 'white'
cols[cols == 'N'] = 'red'
cols[cols == 'P'] = 'blue'

main = paste(processed_pathway_names[ind], "\n",
             'hits =', processed_pathways[[ind]][[3]], "\n",
             'score = ', round(-log10(processed_pathways[[ind]][[4]]), 2))
barplot(shift, main = main, col = cols, cex.axis = 1, cex.names = 0.1, cex.main = 0.8)

sort(processed_pathways[[ind]][[6]][processed_pathways[[ind]][[6]]$prof_index == 3, 'genes'])



selected_pathway_idx = order(additivity_level, decreasing = T)[c(1, 5, 18, 26, 
                                                                 25, 29, 30, 32, 33, 56, 57, 66, 77, 100, 112, 113)]

#selected_pathway_idx = order(additivity_level, decreasing = F)[1:10]

freq_table = processed_pathways[[1]][[8]][1,]
selected_pathways_names = vector()
for (k in 1:length(selected_pathway_idx)){
  
  pathway_info = processed_pathways[[selected_pathway_idx[k]]]
  selected_pathways_names[k] = pathway_info[[1]]
  freq_table = rbind(freq_table, pathway_info[[8]][2,])
  }

selected_pathways_names = gsub("\\(GO:", "", selected_pathways_names, perl=TRUE)

selected_pathways_names = gsub("[0-9]", "", selected_pathways_names, perl=TRUE)

selected_pathways_names = gsub(" \\)", "", selected_pathways_names, perl=TRUE)

freq_table = t(freq_table)

selected_pathways_names[11] = "neg regulat of viral RNA repl via ds-DNA intermediate"
selected_pathways_names[4] = "pos reg of production of siRNA involved in RNA interference"

selected_pathways_names[5] = "neg regulation of NF-kappaB transcription factor activity"

colnames(freq_table) = c("background", selected_pathways_names)
freq_table = freq_table[, rev(1:ncol(freq_table))]


par(mar=c(3.1, 16.5, 1.1, 1.1))
barplot(freq_table, col = c('white', 'red', 'blue'), 
        las = 1, horiz = T, cex.names = 0.7, cex.axis = 0.8,
        font.axis = 3, xlab = 'proportion')

```


```{r warning = FALSE, message = FALSE}
grep('interferon signaling pathway', processed_pathway_names)
ifn_genes = processed_pathways[[99]][[6]]

library(igraph)
#PPI database
ppi = read.csv2('BINARY_PROTEIN_PROTEIN_INTERACTIONS.txt', sep = '\t', stringsAsFactors = FALSE)
ppi_graph = graph_from_edgelist(cbind(as.character(ppi[,1]), as.character(ppi[,4])), directed = FALSE)
ppi_graph = simplify(ppi_graph, remove.loops = T)

ppi_subgraph = induced.subgraph(ppi_graph, which(names(V(ppi_graph)) %in% ifn_genes$genes))

ifn_genes = ifn_genes[order(ifn_genes$genes), ]

new_order = vector()
for (k in 1:nrow(ifn_genes)){
  
  new_order[k] = ifn_genes[ifn_genes$genes == names(V(ppi_subgraph))[k], 'type']
}


custom_layout = layout_in_circle(ppi_subgraph, order = order(new_order))
V(ppi_subgraph)$label.cex = 0.6
V(ppi_subgraph)$label.col = 'black'
V(ppi_subgraph)$label.font = 2
plot(ppi_subgraph, vertex.color = node_color,
     layout = custom_layout)




combined_data_data <- toVisNetworkData(ppi_subgraph)

node_color = rep(NA, nrow(combined_data$nodes))
node_color[combined_data$nodes$id %in% ifn_genes$genes[ifn_genes$type == 'A']] = 'gray'
node_color[combined_data$nodes$id %in% ifn_genes$genes[ifn_genes$type == 'N']] = 'red'
node_color[combined_data$nodes$id %in% ifn_genes$genes[ifn_genes$type == 'P']] = 'blue'

combined_data$nodes$color = node_color
combined_data$nodes$groups = node_color

visNetwork(nodes = combined_data$nodes, edges = combined_data$edges, width = "100%") %>% visIgraphLayout(type = "full") %>%
  visPhysics(timestep = 0) 

```