---
title: "Training and Testing the Classifier"
output: html_document
---

## Generating a training set
```{r setup, include=FALSE}
source("extract_limma_features_v1.R")
source("generate_synthetic_data_v2.R")

PROFCODES = read.table("profile_codes_v2.txt",header = TRUE,sep = "\t") 
expr_range = c(2, 16) 

#generating training set 
ntimes = 300
signal_to_noise_range = c(5, 4, 3, 2)
training_set = generate_synthetic_data_v2(expr_range, ntimes, 
                                         signal_to_noise_range, PROFCODES = PROFCODES)

```


#Training models
```{r setup, include=FALSE}
library(caret)

#train LDA
lda_model = train(training_set[[1]][,-1], 
                  as.factor(training_set[[1]][,1]), 
                  method="lda", preProcess = "pca")

#training KNN
knn_model = train(training_set[[1]][,-1], 
                  as.factor(training_set[[1]][,1]),
                  method = "knn",
                  preProcess = "pca")


#training RandomForest
library(randomForest)

rf_model = randomForest(training_set[[1]][,-1],
                as.factor(training_set[[1]][,1]))

```



#Generating test sets for different noise levels
```{r setup, include=FALSE}
ntimes = 100
signal_to_noise_range = 5
test_5 = generate_synthetic_data_v2(expr_range, ntimes, 
                                         signal_to_noise_range, PROFCODES = PROFCODES)


signal_to_noise_range = 2.5
test_2.5 = generate_synthetic_data_v2(expr_range, ntimes, 
                                         signal_to_noise_range, PROFCODES = PROFCODES)

signal_to_noise_range = 1.5
test_1.5 = generate_synthetic_data_v2(expr_range, ntimes, 
                                         signal_to_noise_range, PROFCODES = PROFCODES)

```



#Testing accuracy
```{r setup, include=FALSE}
source("train_classifiers.R")
source("test_accuracy.R")

#classifiers = train_classifiers(training_set)

classifiers = list(lda_model, knn_model, rf_model)

test_accuracy(classifiers, test_5)
test_accuracy(classifiers, test_2.5)
test_accuracy(classifiers, test_1.5)




cols = c(rgb(1, 0, 0, alpha=0.7), rgb(0, 0, 1, alpha=0.7), rgb(0, 1, 0, alpha=0.7))

par(mar=c(5.02, 6, 4.82, 5.42))

barplot(c(72.498, 0.279, 2.779), col = cols, ylab = 'computational time (s)')
```






```{r setup, include=FALSE}
library(caret)

#train LDA
lda_model = train(training_set[[1]][,-1], 
                  as.factor(training_set[[1]][,1]), 
                  method="lda", preProcess = "pca")

lda_test_5 = diag(table(test_5[[1]][,1], predict(lda_model, test_5[[1]][,-1])))


lda_test_2.5 = diag(table(test_2.5[[1]][,1], predict(lda_model, test_2.5[[1]][,-1])))

lda_test_2.5 = data.frame(as.numeric(lda_test_2.5), "LDA")
names(lda_test_2.5) = c("accuracy", "model")



#training KNN
knn_model = train(training_set[[1]][,-1], 
                  as.factor(training_set[[1]][,1]),
                  method = "knn",
                  preProcess = "pca")

knn_test_5 = diag(table(test_5[[1]][,1], predict(knn_model, test_5[[1]][,-1])))

knn_test_5 = data.frame(as.numeric(knn_test_5), "KNN")
names(knn_test_5) = c("accuracy", "model")


knn_test_2.5 = diag(table(test_2.5[[1]][,1], predict(knn_model, test_2.5[[1]][,-1])))

knn_test_2.5 = data.frame(as.numeric(knn_test_2.5), "KNN")
names(knn_test_2.5) = c("accuracy", "model")



#training RandomForest
library(randomForest)

rf_model = randomForest(training_set[[1]][,-1],
                as.factor(training_set[[1]][,1]))

rf_test_5 = diag(table(test_5[[1]][,1], predict(rf_model,
                                              test_5[[1]][,-1])))

rf_test_5 = data.frame(as.numeric(rf_accuracy_5), "RF")
names(rf_test_5) = c("accuracy", "model")


rf_test_2.5 = diag(table(test_2.5[[1]][,1], predict(rf_model,
                                              test_2.5[[1]][,-1])))

rf_test_2.5 = data.frame(as.numeric(rf_test_2.5), "RF")
names(rf_test_2.5) = c("accuracy", "model")


accuracy_5 = rbind(knn_test_5, lda_test_5, rf_test_5)
density2 <- ggplot(data = accuracy_5, aes(x = accuracy, fill = model)) + geom_density(stat = "density", alpha=I(0.2))
density2 = density2 + facet_grid(model ~ .) + xlab("% accuracy per profile") +   theme_bw() +
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()) 
density2  




accuracy_2.5 = rbind(knn_test_2.5, lda_test_2.5, rf_test_2.5)
density2 <- ggplot(data = accuracy_2.5, aes(x = accuracy, fill = model)) + geom_density(stat = "density", alpha=I(0.2))
density2 = density2 + facet_grid(model ~ .) + xlab("% accuracy per profile") +   theme_bw() +
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()) 
density2  




```