---
title: "X+Y analysis using random forests"
output: html_document
---

### Loading data and independent filtering
The first two columns of the datafile should be annotation (for example probe ID and gene Symbol).
Numerical data start from column 3

```{r message=FALSE, warning=FALSE}
#graphical parameters
source("setPowerPointStyle.R")
setPowerPointStyle()

data_file = "TNF_IFN_2.csv"
my_data = read.csv(data_file,sep = '\t')
head(my_data)

#get numeric data
expression_data = my_data[,-(1:2)]
#log-transform if needed

if (max(expression_data)>25) expression_data = log2(expression_data)

#we assume the same number of samples for each condition
samples = ncol(expression_data)/4

design = c(rep("0", samples), rep("X", samples),
           rep("Y", samples), rep("Y+X", samples))


#removing uninformative probes (very small coefficient of variation)
cof_cutoff = 0.05

cof = apply(expression_data, 1, function(x) sd(x)/mean(x))

cof_filter = which(cof > cof_cutoff)
```


### PCA of samples

```{r message=FALSE, warning=FALSE}
my.pca <- prcomp(t(expression_data[cof_filter, ]), center = TRUE, scale=TRUE)

cols = c(rep("black", samples), rep("red", samples),
                rep("blue", samples), rep("yellow", samples))

plot(my.pca$x[,1], my.pca$x[,2], col = cols,
     xlab = "PC1", ylab = "PC2", pch = 20, cex = 1.5, main = data_file)

legend("bottomleft", pch = 20, col = unique(cols), 
       legend = c("0","X","Y","X+Y"), bty = 'n',cex = 1)

```


### Filtering based on minimum group differences
```{r message=FALSE, warning=FALSE}
source("filter_data_on_deltas.R")

my_data_filtered = filter_data_on_deltas(my_data)
 
head(my_data_filtered)
```
 
### Random forest classifier
```{r message=FALSE, warning=FALSE}
source("find_optimal_match.R")

my_data_filtered_matched = find_optimal_match(my_data_filtered)

head(my_data_filtered_matched)

```

### Visualizing all integration profiles


### Appendix: plotting all profiles
```{r message=FALSE, warning=FALSE}
source("generate_all_profiles.R")
generate_all_profiles()
```